discord:
  prefix: "!"
  logChannelID: "1400454839971876946"
  defaultChannelID: "1379979709055762518"

approval:
  queueChannelID: "1401999939596456047"
  opplysarRoleID: "1381942927294726154"

bannedwords:
  approvalChannelID: "1402312367542374532"  # Production banned word approval channel
  rettskrivarRoleID: "1381943546503761941"  # Production rettskrivar role

grammar:
  channelID: "1402287744985727167"  # Production grammar forum channel

starboard:
  channelID: "1400774666569646111"
  threshold: 1
  emoji: "⭐"  # Production uses ⭐

database:
  host: "malfolketno01.mysql.domeneshop.no"
  port: 3306
  dbname: "malfolketno01"

scheduler:
  enabled: true
  timezone: "Europe/Oslo"
  morning_time: "08:00"     # 08:00 European time
  evening_time: "20:00"     # 20:00 European time
  inactivity_hours: 6       # Post after 6 hours of inactivity
  cron_string: "0 8 * * *"  # Fallback: 08:00 daily

reactions:
  question: "❓"  # Production uses ❓

showAISlopWarning: true
aiSlopWarningText: |
  Denne botten bruker AI-generert kode ("ai slop"). Inntil alt er manuelt sjekket, kan det vere rare eller feilende ting i svaret!
